name: Deploy to VPS
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /apps/enfyra-cms
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            docker build -t enfyra-cms:latest .
            which pulumi || echo "Pulumi not found in PATH"
            ls -la /usr/local/bin/pulumi || echo "Pulumi not in /usr/local/bin"
            ls -la ~/.pulumi/bin/pulumi || echo "Pulumi not in ~/.pulumi/bin"
            export PATH=$PATH:~/.pulumi/bin:/usr/local/bin
            pulumi version
            pulumi stack select enfyra-cms
            pulumi preview
            pulumi up --yes
