name: Deploy to VPS
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            export PATH=$PATH:$HOME/.pulumi/bin

            # Update source code in /apps/enfyra-cms
            cd /apps/enfyra-cms
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            docker build -t enfyra-cms:latest .

            # Run Pulumi in correct directory
            cd /deployments/enfyra-cms
            pulumi version
            pulumi login file://$(pwd)/.pulumi
            pulumi stack select enfyra-cms
            pulumi up --yes
